import { binaryIp, classfulClass, detailsFor, hostId, ipToNumber, isPrivate, numberToIp, sameSubnet, smallestPrefixForHosts } from "@/lib/subnet/calculator";
import type { Difficulty, Question, QuestionType } from "@/types/subnet";

const TYPES: QuestionType[] = ["network", "broadcast", "firstHost", "lastHost", "usableHosts", "totalAddresses", "mask", "wildcard", "cidr", "blockSize", "hostBits", "sameSubnet", "differentSubnet", "nextSubnet", "previousSubnet", "privatePublic", "classful", "binary", "requiredPrefix", "hostId", "vlsm", "longestPrefix"];
const TYPE_LABELS: Record<QuestionType, string> = { network: "Network address", broadcast: "Broadcast address", firstHost: "First usable host", lastHost: "Last usable host", usableHosts: "Usable hosts", totalAddresses: "Total addresses", mask: "Subnet mask", wildcard: "Wildcard mask", cidr: "CIDR prefix", blockSize: "Block size", hostBits: "Host bits", sameSubnet: "Same subnet", differentSubnet: "Different subnet", nextSubnet: "Next subnet", previousSubnet: "Previous subnet", privatePublic: "Private or public", classful: "Classful address", binary: "Binary conversion", requiredPrefix: "Required prefix", hostId: "Host ID", vlsm: "VLSM planning", longestPrefix: "Longest prefix match" };

type Random = () => number;
const pick = <T,>(items: readonly T[], random: Random = Math.random): T => items[Math.floor(random() * items.length)]!;
const seededRandom = (seed: number): Random => { let state = seed >>> 0; return () => { state = (state + 0x6d2b79f5) >>> 0; let value = state; value = Math.imul(value ^ (value >>> 15), value | 1); value ^= value + Math.imul(value ^ (value >>> 7), value | 61); return ((value ^ (value >>> 14)) >>> 0) / 4294967296; }; };
const prefixFor = (difficulty: Difficulty, random: Random): number => pick(difficulty === "Easy" ? [24, 25, 26] : difficulty === "Medium" ? [27, 28, 29] : difficulty === "Hard" ? [22, 23, 24, 25, 26, 27, 28, 29, 30] : [16, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30], random);
function randomIp(random: Random): string { const family = pick([10, 172, 192], random); const second = family === 172 ? 16 + Math.floor(random() * 16) : family === 192 ? 168 : Math.floor(random() * 256); return `${family}.${second}.${Math.floor(random() * 256)}.${Math.floor(random() * 256)}`; }
function answerExplanation(details: ReturnType<typeof detailsFor>): string {
  return `Mask ${details.mask} (/${details.prefix}) leaves ${32 - details.prefix} host bits. The block size is ${details.blockSize}; therefore the network is ${details.network}, broadcast is ${details.broadcast}, and usable hosts range from ${details.firstHost} to ${details.lastHost} (${details.usableHosts.toLocaleString()} usable).`;
}

export function questionTypeLabel(type: QuestionType): string { return TYPE_LABELS[type]; }
export function normalizeAnswer(value: string): string { return value.trim().toLowerCase().replace(/\s+/g, ""); }

export function generateQuestion(difficulty: Difficulty = "Medium", seed?: number): Question {
  const random = seed === undefined ? Math.random : seededRandom(seed); const prefix = prefixFor(difficulty, random); const ip = randomIp(random); const details = detailsFor(ip, prefix); const type = pick(TYPES, random); const summary = answerExplanation(details); const context = `${ip}/${prefix}`;
  const question: Record<QuestionType, Omit<Question, "id" | "type" | "difficulty">> = {
    network: { prompt: "Find the network address", body: `Given ${context}, what is the network address?`, answer: details.network, explanation: summary },
    broadcast: { prompt: "Find the broadcast address", body: `Given ${context}, what is the broadcast address?`, answer: details.broadcast, explanation: summary },
    firstHost: { prompt: "Find the first usable host", body: `Given ${context}, write the first usable host address.`, answer: details.firstHost, explanation: summary },
    lastHost: { prompt: "Find the last usable host", body: `Given ${context}, write the last usable host address.`, answer: details.lastHost, explanation: summary },
    usableHosts: { prompt: "Calculate usable hosts", body: `How many usable host addresses are in ${context}?`, answer: String(details.usableHosts), explanation: summary },
    totalAddresses: { prompt: "Calculate total addresses", body: `How many total addresses does a /${prefix} network contain?`, answer: String(details.totalAddresses), explanation: summary },
    mask: { prompt: "Convert CIDR to a mask", body: `Write the dotted-decimal subnet mask for /${prefix}.`, answer: details.mask, explanation: summary },
    wildcard: { prompt: "Find the wildcard mask", body: `What wildcard mask matches ${context}?`, answer: details.wildcard, explanation: summary },
    cidr: { prompt: "Convert a mask to CIDR", body: `Write the CIDR prefix for ${details.mask}.`, answer: `/${prefix}`, explanation: summary },
    blockSize: { prompt: "Calculate the block size", body: `What is the block size in the interesting octet for ${context}?`, answer: String(details.blockSize), explanation: summary },
    hostBits: { prompt: "Count remaining host bits", body: `How many host bits remain in a /${prefix} prefix?`, answer: String(32 - prefix), explanation: summary },
    sameSubnet: (() => { const peer = numberToIp(ipToNumber(details.network) + Math.min(Math.max(1, details.usableHosts), 5)); return { prompt: "Check network membership", body: `Are ${ip} and ${peer} in the same /${prefix} subnet? Answer yes or no.`, answer: sameSubnet(ip, peer, prefix) ? "yes" : "no", explanation: summary }; })(),
    differentSubnet: (() => { const peer = numberToIp((ipToNumber(details.network) + details.totalAddresses) >>> 0); return { prompt: "Check network membership", body: `Are ${ip} and ${peer} in the same /${prefix} subnet? Answer yes or no.`, answer: "no", explanation: `${peer} starts in the next /${prefix} block. ${summary}` }; })(),
    nextSubnet: { prompt: "Find the next subnet", body: `What network starts immediately after ${details.network}/${prefix}?`, answer: numberToIp(ipToNumber(details.network) + details.totalAddresses), explanation: summary },
    previousSubnet: { prompt: "Find the previous subnet", body: `What network comes immediately before ${details.network}/${prefix}?`, answer: numberToIp(Math.max(0, ipToNumber(details.network) - details.totalAddresses)), explanation: summary },
    privatePublic: { prompt: "Identify the address type", body: `Is ${ip} a private or public IPv4 address?`, answer: isPrivate(ip) ? "private" : "public", explanation: `${ip} is evaluated against RFC 1918 ranges: 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16. ${summary}` },
    classful: { prompt: "Identify the classful address class", body: `Under classful IPv4 rules, what class is ${ip}? Answer A, B, C, D, or E.`, answer: classfulClass(ip), explanation: `The first octet is ${ip.split(".")[0]}. Class A is 0–127, B is 128–191, C is 192–223, D is 224–239, and E is 240–255.` },
    binary: { prompt: "Convert an IPv4 octet to binary", body: `Write the binary representation of the final octet in ${ip}. Use exactly eight bits.`, answer: binaryIp(ip).split(".")[3]!, explanation: `The final octet is ${ip.split(".")[3]}. Converting it to base 2 and padding to eight positions gives ${binaryIp(ip).split(".")[3]}.` },
    requiredPrefix: (() => { const hosts = pick([6, 14, 30, 62, 126, 254, 510], random); const required = smallestPrefixForHosts(hosts); return { prompt: "Choose the smallest valid prefix", body: `What is the smallest IPv4 prefix that supports at least ${hosts} usable hosts?`, answer: `/${required}`, explanation: `A /${required} has ${32 - required} host bits: 2^${32 - required} = ${2 ** (32 - required)} total addresses, leaving ${hosts} or more usable addresses after network and broadcast.` }; })(),
    hostId: { prompt: "Find the host ID", body: `What is the host ID of ${context}?`, answer: hostId(ip, prefix), explanation: `A host ID is the portion where the subnet-mask bits are 0. Applying the wildcard ${details.wildcard} to ${ip} gives ${hostId(ip, prefix)}. ${summary}` },
    vlsm: (() => { const hosts = pick([12, 27, 58, 110, 220], random); const required = smallestPrefixForHosts(hosts); return { prompt: "Plan a VLSM allocation", body: `A branch-office VLAN needs ${hosts} usable addresses. What is the smallest prefix you can allocate?`, answer: `/${required}`, explanation: `Allocate VLSM networks from largest to smallest. ${hosts} hosts need at least ${hosts + 2} total addresses after allowing for network and broadcast. A /${required} provides ${2 ** (32 - required)} total addresses and ${2 ** (32 - required) - 2} usable addresses, so it is the smallest fitting block.` }; })(),
    longestPrefix: (() => { const third = Math.floor(random() * 256); const destination = `10.20.${third}.${Math.floor(random() * 256)}`; const route = `10.20.${third}.0/24`; return { prompt: "Choose the longest prefix match", body: `A router has routes 10.0.0.0/8, 10.20.0.0/16, and ${route}. Which route forwards ${destination}?`, answer: route, explanation: `${destination} matches all three routes, but routing selects the most specific matching prefix. ${route} has 24 network bits, more than /16 and /8, so it wins the longest-prefix-match decision.` }; })(),
  };
  return { id: `${Date.now()}-${crypto.randomUUID()}`, type, difficulty, ...question[type] };
}
